/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InternalFrameProdi.java
 *
 * Created on Dec 20, 2021, 4:29:41 PM
 */
package prodi;

import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import main.CrudPanel;
import tools.CustomizeSwing;

/**
 *
 * @author Rosidin
 */
public class InternalFrameProdi extends javax.swing.JInternalFrame {
    private ProdiTableModel tableModel = new ProdiTableModel();
    private ProdiUnitDialog dlg = new ProdiUnitDialog(this);
    private ProdiController controller = new ProdiController(this, dlg);

    /** Creates new form InternalFrameProdi */
    public InternalFrameProdi() {
        initComponents();  
        initVariables();
    }
    
    private void initVariables() {        
        // tutup windows
        setClosable(true);
        // ukuran maksimal windows
        setMaximizable(true);
        // custom ukuran
        setResizable(true);
        // minimize windows
        setIconifiable(true);
        setTitle("Data Program Studi");
        // buat action listener untuk button baru
        crudPanel.getButtonBaru().addActionListener(controller);
        // buat action listener untuk button edit
        crudPanel.getButtonEdit().addActionListener(controller);  
        // buat action listener untuk button hapus
        crudPanel.getButtonHapus().addActionListener(controller);
        // buat action listener untuk button refresh
        crudPanel.getButtonRefresh().addActionListener(controller);  
        controller.refreshController();
        tableData.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        TableRowSorter sorter = new TableRowSorter(tableModel);
        tableData.setRowSorter(sorter);
        tableData.setModel(tableModel);     
        textCari.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                filterTable(textCari.getText().trim());
            }
            @Override
            public void removeUpdate(DocumentEvent e) {
                filterTable(textCari.getText().trim());
            }
            @Override
            public void changedUpdate(DocumentEvent e) {
                filterTable(textCari.getText().trim());
            }
        });
    }
    
    @SuppressWarnings("unchecked")
    public void filterTable(String text) {
        if (text.trim().equalsIgnoreCase("")) {
            ((TableRowSorter<TableModel>) tableData.getRowSorter()).setRowFilter(null);
        } else {
            ((TableRowSorter<TableModel>) tableData.getRowSorter()).setRowFilter(RowFilter.regexFilter("(?i)"+text));
        }
        CustomizeSwing.autoResizeColumn(tableData);
    }

    public CrudPanel getCrudPanel() {
        return crudPanel;
    }

    public JTable getTableData() {
        return tableData;
    }

    public ProdiTableModel getTableModel() {
        return tableModel;
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crudPanel = new main.CrudPanel();
        textCari = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableData = new javax.swing.JTable();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Cari :");

        tableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableData.setRowHeight(22);
        jScrollPane1.setViewportView(tableData);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textCari, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE))
                    .addComponent(crudPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crudPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private main.CrudPanel crudPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableData;
    private javax.swing.JTextField textCari;
    // End of variables declaration//GEN-END:variables
}
